# Generated by Django 6.0.6 on 2026-06-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Address',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(default=1234567890, max_length=10, verbose_name='Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='unknown', max_length=30, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
